# Picture-in-picture overlays
windowrule {
  name = Picture-in-Picture
  match:title = ([Pp]icture.?in.?[Pp]icture)
  float = true
  pin = true
  size = 600 338
  #keepaspectratio
  #noborder
  opacity = 1 override 1 override
  move = 100%-w-40 4%
}
