windowrule{
    name = Steam main window
    match:class = steam
    match:title = Steam
    float = false
}

windowrule{
    name = Steam
    match:class = steam
    match:fullscreen = true
    idle_inhibit = true
    opacity = 1 1
}

windowrule {
    name = Steam friend list
    match:class = steam
    match:title = Friends List
    float = true
    opacity = 1 1
    size = 460 800
  }
