# Webcam overlay for screen recording
windowrule{
  name = Webcam overlay
  match:title = WebcamOverlay
  float = true
  pin = true
  no_initial_focus = true
  no_dim = true
  move = 100%-w-40 100%-w-40
}
